eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8233
spring:
  management:
    tracing:
      sampling:
        probability: 1.0
  application:
    name: details
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1236/details
    username: postgres
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

