eureka:
  client:
    register-with-eureka: false
server:
  port: 8111

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/student/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/school/**
        - id: details
          uri: http://localhost:8233
          predicates:
            - Path=/details/**
  management:
    tracing:
      sampling:
        probability: 1.0
