eureka:
  client:
    register-with-eureka: false
server:
  port: 8111

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/student/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/school/**
